FROM rust:slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    mold && rm -rf /var/lib/apt/lists/*

COPY --chmod=755 ./watch.sh /watch.sh

ENTRYPOINT [ "/watch.sh" ]

CMD [ "-x", "run" ]
